/* 
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * OpenAPI spec version: 2.3.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AgentsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AgentsApiTests
    {
        private AgentsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AgentsApi();
            instance.Configuration.AccessToken = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWVyIjoiV0lMTF9OT1JUT04iLCJ2ZXJzaW9uIjoidjIuMy4wIiwicmVzZXRfZGF0ZSI6IjIwMjUtMTAtMTkiLCJpYXQiOjE3NjExNzYwNTgsInN1YiI6ImFnZW50LXRva2VuIn0.D_11yzfvv3ciDMfirW1cJwo--gZsYLPpDKmyOTiplNoRo3Xxt3mXW-cdG1qbxliuh1Fqxlo6cy50LwpTYPI9Gt29SYZfSaGhKPoJOP0zuA4H9lrmtj8jkibDZZSQ5dNNXGGN81g8asr_e2s38QaQ72G-bJx3eZYHvh1Lcka53uedBjLM942qGqs-0kQMI_hYMR2NMN6GpPXYTDAE-jeQ0pfzf3EAQ1Dcm25JoPnNQZ334MtEcflPNMJ8ZZf8FolLE16Ev5krjVGPu45F0gdfHfIlV83zxHrS0uwsDvkPfNVH1bfzdBRqQ-SAT1CtxyAxr-H1PfMwAyX2vAgaVT5u8U7y4PzzZgfC5a8DJMAub9_P2A7MHB7SBEeBQgdcbFRk5Z5aIrtehKBgOaQQsj9EFS5G8FNZVLqk4Fkrr_CGTTQ3YRser9HvV3Ymuon2EsWqqXNP9qxWPtAITWWjbORqoI1YHDsusHLfHX6_1JiSBbUC0Ous2GuOarnc6aXhgzxNNEU9EFBzqLkKoMTvjlMxhGPjno7nVSwNjzSc7L5WyzemDjRyNyxEcR5RN15ffLGMhJOgF1QCAeab7tphCzVWEbr8TjfPZT4KlffvObW-QgfUAmUXEJQkf4O_jDFwyFe3IR9H9Li7eFNtUGDJ1kY8UFS5KO4D-ngtCEdG1dEWlgg";
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AgentsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AgentsApi
            //Assert.IsInstanceOfType(typeof(AgentsApi), instance, "instance is a AgentsApi");
        }

        /// <summary>
        /// Test GetAgent
        /// </summary>
        [Test]
        public void GetAgentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string agentSymbol = null;
            //var response = instance.GetAgent(agentSymbol);
            //Assert.IsInstanceOf<InlineResponse20011> (response, "response is InlineResponse20011");
        }
        /// <summary>
        /// Test GetAgents
        /// </summary>
        [Test]
        public void GetAgentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? limit = null;
            //var response = instance.GetAgents(page, limit);
            //Assert.IsInstanceOf<InlineResponse20012> (response, "response is InlineResponse20012");
        }
        /// <summary>
        /// Test GetMyAgent
        /// </summary>
        [Test]
        public void GetMyAgentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            InlineResponse20011 response = instance.GetMyAgent();
            Agent agent = response.Data;
        }
    }

}
