/* 
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * OpenAPI spec version: 2.3.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ContractsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ContractsApiTests
    {
        private ContractsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ContractsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ContractsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ContractsApi
            //Assert.IsInstanceOfType(typeof(ContractsApi), instance, "instance is a ContractsApi");
        }

        /// <summary>
        /// Test AcceptContract
        /// </summary>
        [Test]
        public void AcceptContractTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string contractId = null;
            //var response = instance.AcceptContract(contractId);
            //Assert.IsInstanceOf<InlineResponse20015> (response, "response is InlineResponse20015");
        }
        /// <summary>
        /// Test DeliverContract
        /// </summary>
        [Test]
        public void DeliverContractTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string contractId = null;
            //ContractIdDeliverBody body = null;
            //var response = instance.DeliverContract(contractId, body);
            //Assert.IsInstanceOf<InlineResponse20016> (response, "response is InlineResponse20016");
        }
        /// <summary>
        /// Test FulfillContract
        /// </summary>
        [Test]
        public void FulfillContractTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string contractId = null;
            //var response = instance.FulfillContract(contractId);
            //Assert.IsInstanceOf<InlineResponse20017> (response, "response is InlineResponse20017");
        }
        /// <summary>
        /// Test GetContract
        /// </summary>
        [Test]
        public void GetContractTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string contractId = null;
            //var response = instance.GetContract(contractId);
            //Assert.IsInstanceOf<InlineResponse20014> (response, "response is InlineResponse20014");
        }
        /// <summary>
        /// Test GetContracts
        /// </summary>
        [Test]
        public void GetContractsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? limit = null;
            //var response = instance.GetContracts(page, limit);
            //Assert.IsInstanceOf<InlineResponse20013> (response, "response is InlineResponse20013");
        }
    }

}
