/* 
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * OpenAPI spec version: 2.3.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// The details of the required construction materials for a given waypoint under construction.
    /// </summary>
    [DataContract]
        public partial class ConstructionMaterial :  IEquatable<ConstructionMaterial>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConstructionMaterial" /> class.
        /// </summary>
        /// <param name="tradeSymbol">tradeSymbol (required).</param>
        /// <param name="required">The number of units required. (required).</param>
        /// <param name="fulfilled">The number of units fulfilled toward the required amount. (required).</param>
        public ConstructionMaterial(TradeSymbol tradeSymbol = default(TradeSymbol), int? required = default(int?), int? fulfilled = default(int?))
        {
            // to ensure "tradeSymbol" is required (not null)
            if (tradeSymbol == null)
            {
                throw new InvalidDataException("tradeSymbol is a required property for ConstructionMaterial and cannot be null");
            }
            else
            {
                this.TradeSymbol = tradeSymbol;
            }
            // to ensure "required" is required (not null)
            if (required == null)
            {
                throw new InvalidDataException("required is a required property for ConstructionMaterial and cannot be null");
            }
            else
            {
                this.Required = required;
            }
            // to ensure "fulfilled" is required (not null)
            if (fulfilled == null)
            {
                throw new InvalidDataException("fulfilled is a required property for ConstructionMaterial and cannot be null");
            }
            else
            {
                this.Fulfilled = fulfilled;
            }
        }
        
        /// <summary>
        /// Gets or Sets TradeSymbol
        /// </summary>
        [DataMember(Name="tradeSymbol", EmitDefaultValue=false)]
        public TradeSymbol TradeSymbol { get; set; }

        /// <summary>
        /// The number of units required.
        /// </summary>
        /// <value>The number of units required.</value>
        [DataMember(Name="required", EmitDefaultValue=false)]
        public int? Required { get; set; }

        /// <summary>
        /// The number of units fulfilled toward the required amount.
        /// </summary>
        /// <value>The number of units fulfilled toward the required amount.</value>
        [DataMember(Name="fulfilled", EmitDefaultValue=false)]
        public int? Fulfilled { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ConstructionMaterial {\n");
            sb.Append("  TradeSymbol: ").Append(TradeSymbol).Append("\n");
            sb.Append("  Required: ").Append(Required).Append("\n");
            sb.Append("  Fulfilled: ").Append(Fulfilled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ConstructionMaterial);
        }

        /// <summary>
        /// Returns true if ConstructionMaterial instances are equal
        /// </summary>
        /// <param name="input">Instance of ConstructionMaterial to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ConstructionMaterial input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TradeSymbol == input.TradeSymbol ||
                    (this.TradeSymbol != null &&
                    this.TradeSymbol.Equals(input.TradeSymbol))
                ) && 
                (
                    this.Required == input.Required ||
                    (this.Required != null &&
                    this.Required.Equals(input.Required))
                ) && 
                (
                    this.Fulfilled == input.Fulfilled ||
                    (this.Fulfilled != null &&
                    this.Fulfilled.Equals(input.Fulfilled))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TradeSymbol != null)
                    hashCode = hashCode * 59 + this.TradeSymbol.GetHashCode();
                if (this.Required != null)
                    hashCode = hashCode * 59 + this.Required.GetHashCode();
                if (this.Fulfilled != null)
                    hashCode = hashCode * 59 + this.Fulfilled.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
