/* 
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * OpenAPI spec version: 2.3.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// InlineResponse200
    /// </summary>
    [DataContract]
        public partial class InlineResponse200 :  IEquatable<InlineResponse200>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse200" /> class.
        /// </summary>
        /// <param name="status">The current status of the game server. (required).</param>
        /// <param name="version">The current version of the API. (required).</param>
        /// <param name="resetDate">The date when the game server was last reset. (required).</param>
        /// <param name="description">description (required).</param>
        /// <param name="stats">stats (required).</param>
        /// <param name="leaderboards">leaderboards (required).</param>
        /// <param name="serverResets">serverResets (required).</param>
        /// <param name="announcements">announcements (required).</param>
        /// <param name="links">links (required).</param>
        public InlineResponse200(string status = default(string), string version = default(string), string resetDate = default(string), string description = default(string), InlineResponse200Stats stats = default(InlineResponse200Stats), InlineResponse200Leaderboards leaderboards = default(InlineResponse200Leaderboards), InlineResponse200ServerResets serverResets = default(InlineResponse200ServerResets), List<InlineResponse200Announcements> announcements = default(List<InlineResponse200Announcements>), List<InlineResponse200Links> links = default(List<InlineResponse200Links>))
        {
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new InvalidDataException("status is a required property for InlineResponse200 and cannot be null");
            }
            else
            {
                this.Status = status;
            }
            // to ensure "version" is required (not null)
            if (version == null)
            {
                throw new InvalidDataException("version is a required property for InlineResponse200 and cannot be null");
            }
            else
            {
                this.Version = version;
            }
            // to ensure "resetDate" is required (not null)
            if (resetDate == null)
            {
                throw new InvalidDataException("resetDate is a required property for InlineResponse200 and cannot be null");
            }
            else
            {
                this.ResetDate = resetDate;
            }
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new InvalidDataException("description is a required property for InlineResponse200 and cannot be null");
            }
            else
            {
                this.Description = description;
            }
            // to ensure "stats" is required (not null)
            if (stats == null)
            {
                throw new InvalidDataException("stats is a required property for InlineResponse200 and cannot be null");
            }
            else
            {
                this.Stats = stats;
            }
            // to ensure "leaderboards" is required (not null)
            if (leaderboards == null)
            {
                throw new InvalidDataException("leaderboards is a required property for InlineResponse200 and cannot be null");
            }
            else
            {
                this.Leaderboards = leaderboards;
            }
            // to ensure "serverResets" is required (not null)
            if (serverResets == null)
            {
                throw new InvalidDataException("serverResets is a required property for InlineResponse200 and cannot be null");
            }
            else
            {
                this.ServerResets = serverResets;
            }
            // to ensure "announcements" is required (not null)
            if (announcements == null)
            {
                throw new InvalidDataException("announcements is a required property for InlineResponse200 and cannot be null");
            }
            else
            {
                this.Announcements = announcements;
            }
            // to ensure "links" is required (not null)
            if (links == null)
            {
                throw new InvalidDataException("links is a required property for InlineResponse200 and cannot be null");
            }
            else
            {
                this.Links = links;
            }
        }
        
        /// <summary>
        /// The current status of the game server.
        /// </summary>
        /// <value>The current status of the game server.</value>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public string Status { get; set; }

        /// <summary>
        /// The current version of the API.
        /// </summary>
        /// <value>The current version of the API.</value>
        [DataMember(Name="version", EmitDefaultValue=false)]
        public string Version { get; set; }

        /// <summary>
        /// The date when the game server was last reset.
        /// </summary>
        /// <value>The date when the game server was last reset.</value>
        [DataMember(Name="resetDate", EmitDefaultValue=false)]
        public string ResetDate { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Stats
        /// </summary>
        [DataMember(Name="stats", EmitDefaultValue=false)]
        public InlineResponse200Stats Stats { get; set; }

        /// <summary>
        /// Gets or Sets Leaderboards
        /// </summary>
        [DataMember(Name="leaderboards", EmitDefaultValue=false)]
        public InlineResponse200Leaderboards Leaderboards { get; set; }

        /// <summary>
        /// Gets or Sets ServerResets
        /// </summary>
        [DataMember(Name="serverResets", EmitDefaultValue=false)]
        public InlineResponse200ServerResets ServerResets { get; set; }

        /// <summary>
        /// Gets or Sets Announcements
        /// </summary>
        [DataMember(Name="announcements", EmitDefaultValue=false)]
        public List<InlineResponse200Announcements> Announcements { get; set; }

        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [DataMember(Name="links", EmitDefaultValue=false)]
        public List<InlineResponse200Links> Links { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse200 {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Version: ").Append(Version).Append("\n");
            sb.Append("  ResetDate: ").Append(ResetDate).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Stats: ").Append(Stats).Append("\n");
            sb.Append("  Leaderboards: ").Append(Leaderboards).Append("\n");
            sb.Append("  ServerResets: ").Append(ServerResets).Append("\n");
            sb.Append("  Announcements: ").Append(Announcements).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponse200);
        }

        /// <summary>
        /// Returns true if InlineResponse200 instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponse200 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse200 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.Version == input.Version ||
                    (this.Version != null &&
                    this.Version.Equals(input.Version))
                ) && 
                (
                    this.ResetDate == input.ResetDate ||
                    (this.ResetDate != null &&
                    this.ResetDate.Equals(input.ResetDate))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.Stats == input.Stats ||
                    (this.Stats != null &&
                    this.Stats.Equals(input.Stats))
                ) && 
                (
                    this.Leaderboards == input.Leaderboards ||
                    (this.Leaderboards != null &&
                    this.Leaderboards.Equals(input.Leaderboards))
                ) && 
                (
                    this.ServerResets == input.ServerResets ||
                    (this.ServerResets != null &&
                    this.ServerResets.Equals(input.ServerResets))
                ) && 
                (
                    this.Announcements == input.Announcements ||
                    this.Announcements != null &&
                    input.Announcements != null &&
                    this.Announcements.SequenceEqual(input.Announcements)
                ) && 
                (
                    this.Links == input.Links ||
                    this.Links != null &&
                    input.Links != null &&
                    this.Links.SequenceEqual(input.Links)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.Version != null)
                    hashCode = hashCode * 59 + this.Version.GetHashCode();
                if (this.ResetDate != null)
                    hashCode = hashCode * 59 + this.ResetDate.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.Stats != null)
                    hashCode = hashCode * 59 + this.Stats.GetHashCode();
                if (this.Leaderboards != null)
                    hashCode = hashCode * 59 + this.Leaderboards.GetHashCode();
                if (this.ServerResets != null)
                    hashCode = hashCode * 59 + this.ServerResets.GetHashCode();
                if (this.Announcements != null)
                    hashCode = hashCode * 59 + this.Announcements.GetHashCode();
                if (this.Links != null)
                    hashCode = hashCode * 59 + this.Links.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
