/* 
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * OpenAPI spec version: 2.3.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// InlineResponse2015Data
    /// </summary>
    [DataContract]
        public partial class InlineResponse2015Data :  IEquatable<InlineResponse2015Data>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse2015Data" /> class.
        /// </summary>
        /// <param name="cooldown">cooldown (required).</param>
        /// <param name="extraction">extraction (required).</param>
        /// <param name="cargo">cargo (required).</param>
        /// <param name="modifiers">modifiers.</param>
        /// <param name="events">events (required).</param>
        public InlineResponse2015Data(Cooldown cooldown = default(Cooldown), Extraction extraction = default(Extraction), ShipCargo cargo = default(ShipCargo), List<WaypointModifier> modifiers = default(List<WaypointModifier>), List<ShipConditionEvent> events = default(List<ShipConditionEvent>))
        {
            // to ensure "cooldown" is required (not null)
            if (cooldown == null)
            {
                throw new InvalidDataException("cooldown is a required property for InlineResponse2015Data and cannot be null");
            }
            else
            {
                this.Cooldown = cooldown;
            }
            // to ensure "extraction" is required (not null)
            if (extraction == null)
            {
                throw new InvalidDataException("extraction is a required property for InlineResponse2015Data and cannot be null");
            }
            else
            {
                this.Extraction = extraction;
            }
            // to ensure "cargo" is required (not null)
            if (cargo == null)
            {
                throw new InvalidDataException("cargo is a required property for InlineResponse2015Data and cannot be null");
            }
            else
            {
                this.Cargo = cargo;
            }
            // to ensure "events" is required (not null)
            if (events == null)
            {
                throw new InvalidDataException("events is a required property for InlineResponse2015Data and cannot be null");
            }
            else
            {
                this.Events = events;
            }
            this.Modifiers = modifiers;
        }
        
        /// <summary>
        /// Gets or Sets Cooldown
        /// </summary>
        [DataMember(Name="cooldown", EmitDefaultValue=false)]
        public Cooldown Cooldown { get; set; }

        /// <summary>
        /// Gets or Sets Extraction
        /// </summary>
        [DataMember(Name="extraction", EmitDefaultValue=false)]
        public Extraction Extraction { get; set; }

        /// <summary>
        /// Gets or Sets Cargo
        /// </summary>
        [DataMember(Name="cargo", EmitDefaultValue=false)]
        public ShipCargo Cargo { get; set; }

        /// <summary>
        /// Gets or Sets Modifiers
        /// </summary>
        [DataMember(Name="modifiers", EmitDefaultValue=false)]
        public List<WaypointModifier> Modifiers { get; set; }

        /// <summary>
        /// Gets or Sets Events
        /// </summary>
        [DataMember(Name="events", EmitDefaultValue=false)]
        public List<ShipConditionEvent> Events { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse2015Data {\n");
            sb.Append("  Cooldown: ").Append(Cooldown).Append("\n");
            sb.Append("  Extraction: ").Append(Extraction).Append("\n");
            sb.Append("  Cargo: ").Append(Cargo).Append("\n");
            sb.Append("  Modifiers: ").Append(Modifiers).Append("\n");
            sb.Append("  Events: ").Append(Events).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponse2015Data);
        }

        /// <summary>
        /// Returns true if InlineResponse2015Data instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponse2015Data to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse2015Data input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Cooldown == input.Cooldown ||
                    (this.Cooldown != null &&
                    this.Cooldown.Equals(input.Cooldown))
                ) && 
                (
                    this.Extraction == input.Extraction ||
                    (this.Extraction != null &&
                    this.Extraction.Equals(input.Extraction))
                ) && 
                (
                    this.Cargo == input.Cargo ||
                    (this.Cargo != null &&
                    this.Cargo.Equals(input.Cargo))
                ) && 
                (
                    this.Modifiers == input.Modifiers ||
                    this.Modifiers != null &&
                    input.Modifiers != null &&
                    this.Modifiers.SequenceEqual(input.Modifiers)
                ) && 
                (
                    this.Events == input.Events ||
                    this.Events != null &&
                    input.Events != null &&
                    this.Events.SequenceEqual(input.Events)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Cooldown != null)
                    hashCode = hashCode * 59 + this.Cooldown.GetHashCode();
                if (this.Extraction != null)
                    hashCode = hashCode * 59 + this.Extraction.GetHashCode();
                if (this.Cargo != null)
                    hashCode = hashCode * 59 + this.Cargo.GetHashCode();
                if (this.Modifiers != null)
                    hashCode = hashCode * 59 + this.Modifiers.GetHashCode();
                if (this.Events != null)
                    hashCode = hashCode * 59 + this.Events.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
