/* 
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * OpenAPI spec version: 2.3.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// InlineResponse2019Data
    /// </summary>
    [DataContract]
        public partial class InlineResponse2019Data :  IEquatable<InlineResponse2019Data>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse2019Data" /> class.
        /// </summary>
        /// <param name="cooldown">cooldown (required).</param>
        /// <param name="waypoints">List of scanned waypoints. (required).</param>
        public InlineResponse2019Data(Cooldown cooldown = default(Cooldown), List<ScannedWaypoint> waypoints = default(List<ScannedWaypoint>))
        {
            // to ensure "cooldown" is required (not null)
            if (cooldown == null)
            {
                throw new InvalidDataException("cooldown is a required property for InlineResponse2019Data and cannot be null");
            }
            else
            {
                this.Cooldown = cooldown;
            }
            // to ensure "waypoints" is required (not null)
            if (waypoints == null)
            {
                throw new InvalidDataException("waypoints is a required property for InlineResponse2019Data and cannot be null");
            }
            else
            {
                this.Waypoints = waypoints;
            }
        }
        
        /// <summary>
        /// Gets or Sets Cooldown
        /// </summary>
        [DataMember(Name="cooldown", EmitDefaultValue=false)]
        public Cooldown Cooldown { get; set; }

        /// <summary>
        /// List of scanned waypoints.
        /// </summary>
        /// <value>List of scanned waypoints.</value>
        [DataMember(Name="waypoints", EmitDefaultValue=false)]
        public List<ScannedWaypoint> Waypoints { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse2019Data {\n");
            sb.Append("  Cooldown: ").Append(Cooldown).Append("\n");
            sb.Append("  Waypoints: ").Append(Waypoints).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponse2019Data);
        }

        /// <summary>
        /// Returns true if InlineResponse2019Data instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponse2019Data to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse2019Data input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Cooldown == input.Cooldown ||
                    (this.Cooldown != null &&
                    this.Cooldown.Equals(input.Cooldown))
                ) && 
                (
                    this.Waypoints == input.Waypoints ||
                    this.Waypoints != null &&
                    input.Waypoints != null &&
                    this.Waypoints.SequenceEqual(input.Waypoints)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Cooldown != null)
                    hashCode = hashCode * 59 + this.Cooldown.GetHashCode();
                if (this.Waypoints != null)
                    hashCode = hashCode * 59 + this.Waypoints.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
