/* 
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * OpenAPI spec version: 2.3.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// RegisterBody
    /// </summary>
    [DataContract]
        public partial class RegisterBody :  IEquatable<RegisterBody>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RegisterBody" /> class.
        /// </summary>
        /// <param name="faction">faction (required).</param>
        /// <param name="symbol">Your desired agent symbol. This will be a unique name used to represent your agent, and will be the prefix for your ships. (required).</param>
        /// <param name="email">Your email address. This is used if you reserved your call sign between resets..</param>
        public RegisterBody(FactionSymbol faction = default(FactionSymbol), string symbol = default(string), string email = default(string))
        {
            // to ensure "faction" is required (not null)
            if (faction == null)
            {
                throw new InvalidDataException("faction is a required property for RegisterBody and cannot be null");
            }
            else
            {
                this.Faction = faction;
            }
            // to ensure "symbol" is required (not null)
            if (symbol == null)
            {
                throw new InvalidDataException("symbol is a required property for RegisterBody and cannot be null");
            }
            else
            {
                this.Symbol = symbol;
            }
            this.Email = email;
        }
        
        /// <summary>
        /// Gets or Sets Faction
        /// </summary>
        [DataMember(Name="faction", EmitDefaultValue=false)]
        public FactionSymbol Faction { get; set; }

        /// <summary>
        /// Your desired agent symbol. This will be a unique name used to represent your agent, and will be the prefix for your ships.
        /// </summary>
        /// <value>Your desired agent symbol. This will be a unique name used to represent your agent, and will be the prefix for your ships.</value>
        [DataMember(Name="symbol", EmitDefaultValue=false)]
        public string Symbol { get; set; }

        /// <summary>
        /// Your email address. This is used if you reserved your call sign between resets.
        /// </summary>
        /// <value>Your email address. This is used if you reserved your call sign between resets.</value>
        [DataMember(Name="email", EmitDefaultValue=false)]
        public string Email { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RegisterBody {\n");
            sb.Append("  Faction: ").Append(Faction).Append("\n");
            sb.Append("  Symbol: ").Append(Symbol).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RegisterBody);
        }

        /// <summary>
        /// Returns true if RegisterBody instances are equal
        /// </summary>
        /// <param name="input">Instance of RegisterBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RegisterBody input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Faction == input.Faction ||
                    (this.Faction != null &&
                    this.Faction.Equals(input.Faction))
                ) && 
                (
                    this.Symbol == input.Symbol ||
                    (this.Symbol != null &&
                    this.Symbol.Equals(input.Symbol))
                ) && 
                (
                    this.Email == input.Email ||
                    (this.Email != null &&
                    this.Email.Equals(input.Email))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Faction != null)
                    hashCode = hashCode * 59 + this.Faction.GetHashCode();
                if (this.Symbol != null)
                    hashCode = hashCode * 59 + this.Symbol.GetHashCode();
                if (this.Email != null)
                    hashCode = hashCode * 59 + this.Email.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
