/* 
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * OpenAPI spec version: 2.3.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// The reactor of the ship. The reactor is responsible for powering the ship&#x27;s systems and weapons.
    /// </summary>
    [DataContract]
        public partial class ShipReactor :  IEquatable<ShipReactor>, IValidatableObject
    {
        /// <summary>
        /// Symbol of the reactor.
        /// </summary>
        /// <value>Symbol of the reactor.</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum SymbolEnum
        {
            /// <summary>
            /// Enum SOLARI for value: REACTOR_SOLAR_I
            /// </summary>
            [EnumMember(Value = "REACTOR_SOLAR_I")]
            SOLARI = 1,
            /// <summary>
            /// Enum FUSIONI for value: REACTOR_FUSION_I
            /// </summary>
            [EnumMember(Value = "REACTOR_FUSION_I")]
            FUSIONI = 2,
            /// <summary>
            /// Enum FISSIONI for value: REACTOR_FISSION_I
            /// </summary>
            [EnumMember(Value = "REACTOR_FISSION_I")]
            FISSIONI = 3,
            /// <summary>
            /// Enum CHEMICALI for value: REACTOR_CHEMICAL_I
            /// </summary>
            [EnumMember(Value = "REACTOR_CHEMICAL_I")]
            CHEMICALI = 4,
            /// <summary>
            /// Enum ANTIMATTERI for value: REACTOR_ANTIMATTER_I
            /// </summary>
            [EnumMember(Value = "REACTOR_ANTIMATTER_I")]
            ANTIMATTERI = 5        }
        /// <summary>
        /// Symbol of the reactor.
        /// </summary>
        /// <value>Symbol of the reactor.</value>
        [DataMember(Name="symbol", EmitDefaultValue=false)]
        public SymbolEnum Symbol { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ShipReactor" /> class.
        /// </summary>
        /// <param name="symbol">Symbol of the reactor. (required).</param>
        /// <param name="name">Name of the reactor. (required).</param>
        /// <param name="description">Description of the reactor. (required).</param>
        /// <param name="condition">condition (required).</param>
        /// <param name="integrity">integrity (required).</param>
        /// <param name="powerOutput">The amount of power provided by this reactor. The more power a reactor provides to the ship, the lower the cooldown it gets when using a module or mount that taxes the ship&#x27;s power. (required).</param>
        /// <param name="requirements">requirements (required).</param>
        /// <param name="quality">quality (required).</param>
        public ShipReactor(SymbolEnum symbol = default(SymbolEnum), string name = default(string), string description = default(string), double? condition = default(double?), double? integrity = default(double?), int? powerOutput = default(int?), ShipRequirements requirements = default(ShipRequirements), decimal? quality = default(decimal?))
        {
            // to ensure "symbol" is required (not null)
            if (symbol == null)
            {
                throw new InvalidDataException("symbol is a required property for ShipReactor and cannot be null");
            }
            else
            {
                this.Symbol = symbol;
            }
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for ShipReactor and cannot be null");
            }
            else
            {
                this.Name = name;
            }
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new InvalidDataException("description is a required property for ShipReactor and cannot be null");
            }
            else
            {
                this.Description = description;
            }
            // to ensure "condition" is required (not null)
            if (condition == null)
            {
                throw new InvalidDataException("condition is a required property for ShipReactor and cannot be null");
            }
            else
            {
                this.Condition = condition;
            }
            // to ensure "integrity" is required (not null)
            if (integrity == null)
            {
                throw new InvalidDataException("integrity is a required property for ShipReactor and cannot be null");
            }
            else
            {
                this.Integrity = integrity;
            }
            // to ensure "powerOutput" is required (not null)
            if (powerOutput == null)
            {
                throw new InvalidDataException("powerOutput is a required property for ShipReactor and cannot be null");
            }
            else
            {
                this.PowerOutput = powerOutput;
            }
            // to ensure "requirements" is required (not null)
            if (requirements == null)
            {
                throw new InvalidDataException("requirements is a required property for ShipReactor and cannot be null");
            }
            else
            {
                this.Requirements = requirements;
            }
            // to ensure "quality" is required (not null)
            if (quality == null)
            {
                throw new InvalidDataException("quality is a required property for ShipReactor and cannot be null");
            }
            else
            {
                this.Quality = quality;
            }
        }
        

        /// <summary>
        /// Name of the reactor.
        /// </summary>
        /// <value>Name of the reactor.</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Description of the reactor.
        /// </summary>
        /// <value>Description of the reactor.</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Condition
        /// </summary>
        [DataMember(Name="condition", EmitDefaultValue=false)]
        public double? Condition { get; set; }

        /// <summary>
        /// Gets or Sets Integrity
        /// </summary>
        [DataMember(Name="integrity", EmitDefaultValue=false)]
        public double? Integrity { get; set; }

        /// <summary>
        /// The amount of power provided by this reactor. The more power a reactor provides to the ship, the lower the cooldown it gets when using a module or mount that taxes the ship&#x27;s power.
        /// </summary>
        /// <value>The amount of power provided by this reactor. The more power a reactor provides to the ship, the lower the cooldown it gets when using a module or mount that taxes the ship&#x27;s power.</value>
        [DataMember(Name="powerOutput", EmitDefaultValue=false)]
        public int? PowerOutput { get; set; }

        /// <summary>
        /// Gets or Sets Requirements
        /// </summary>
        [DataMember(Name="requirements", EmitDefaultValue=false)]
        public ShipRequirements Requirements { get; set; }

        /// <summary>
        /// Gets or Sets Quality
        /// </summary>
        [DataMember(Name="quality", EmitDefaultValue=false)]
        public decimal? Quality { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ShipReactor {\n");
            sb.Append("  Symbol: ").Append(Symbol).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Condition: ").Append(Condition).Append("\n");
            sb.Append("  Integrity: ").Append(Integrity).Append("\n");
            sb.Append("  PowerOutput: ").Append(PowerOutput).Append("\n");
            sb.Append("  Requirements: ").Append(Requirements).Append("\n");
            sb.Append("  Quality: ").Append(Quality).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ShipReactor);
        }

        /// <summary>
        /// Returns true if ShipReactor instances are equal
        /// </summary>
        /// <param name="input">Instance of ShipReactor to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ShipReactor input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Symbol == input.Symbol ||
                    (this.Symbol != null &&
                    this.Symbol.Equals(input.Symbol))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.Condition == input.Condition ||
                    (this.Condition != null &&
                    this.Condition.Equals(input.Condition))
                ) && 
                (
                    this.Integrity == input.Integrity ||
                    (this.Integrity != null &&
                    this.Integrity.Equals(input.Integrity))
                ) && 
                (
                    this.PowerOutput == input.PowerOutput ||
                    (this.PowerOutput != null &&
                    this.PowerOutput.Equals(input.PowerOutput))
                ) && 
                (
                    this.Requirements == input.Requirements ||
                    (this.Requirements != null &&
                    this.Requirements.Equals(input.Requirements))
                ) && 
                (
                    this.Quality == input.Quality ||
                    (this.Quality != null &&
                    this.Quality.Equals(input.Quality))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Symbol != null)
                    hashCode = hashCode * 59 + this.Symbol.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.Condition != null)
                    hashCode = hashCode * 59 + this.Condition.GetHashCode();
                if (this.Integrity != null)
                    hashCode = hashCode * 59 + this.Integrity.GetHashCode();
                if (this.PowerOutput != null)
                    hashCode = hashCode * 59 + this.PowerOutput.GetHashCode();
                if (this.Requirements != null)
                    hashCode = hashCode * 59 + this.Requirements.GetHashCode();
                if (this.Quality != null)
                    hashCode = hashCode * 59 + this.Quality.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
