/* 
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * OpenAPI spec version: 2.3.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Waypoint details.
    /// </summary>
    [DataContract]
        public partial class SystemWaypoint :  IEquatable<SystemWaypoint>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SystemWaypoint" /> class.
        /// </summary>
        /// <param name="symbol">symbol (required).</param>
        /// <param name="type">type (required).</param>
        /// <param name="x">Relative position of the waypoint on the system&#x27;s x axis. This is not an absolute position in the universe. (required).</param>
        /// <param name="y">Relative position of the waypoint on the system&#x27;s y axis. This is not an absolute position in the universe. (required).</param>
        /// <param name="orbitals">Waypoints that orbit this waypoint. (required).</param>
        /// <param name="orbits">The symbol of the parent waypoint, if this waypoint is in orbit around another waypoint. Otherwise this value is undefined..</param>
        public SystemWaypoint(string symbol = default(string), WaypointType type = default(WaypointType), int? x = default(int?), int? y = default(int?), List<WaypointOrbital> orbitals = default(List<WaypointOrbital>), string orbits = default(string))
        {
            // to ensure "symbol" is required (not null)
            if (symbol == null)
            {
                throw new InvalidDataException("symbol is a required property for SystemWaypoint and cannot be null");
            }
            else
            {
                this.Symbol = symbol;
            }
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new InvalidDataException("type is a required property for SystemWaypoint and cannot be null");
            }
            else
            {
                this.Type = type;
            }
            // to ensure "x" is required (not null)
            if (x == null)
            {
                throw new InvalidDataException("x is a required property for SystemWaypoint and cannot be null");
            }
            else
            {
                this.X = x;
            }
            // to ensure "y" is required (not null)
            if (y == null)
            {
                throw new InvalidDataException("y is a required property for SystemWaypoint and cannot be null");
            }
            else
            {
                this.Y = y;
            }
            // to ensure "orbitals" is required (not null)
            if (orbitals == null)
            {
                throw new InvalidDataException("orbitals is a required property for SystemWaypoint and cannot be null");
            }
            else
            {
                this.Orbitals = orbitals;
            }
            this.Orbits = orbits;
        }
        
        /// <summary>
        /// Gets or Sets Symbol
        /// </summary>
        [DataMember(Name="symbol", EmitDefaultValue=false)]
        public string Symbol { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public WaypointType Type { get; set; }

        /// <summary>
        /// Relative position of the waypoint on the system&#x27;s x axis. This is not an absolute position in the universe.
        /// </summary>
        /// <value>Relative position of the waypoint on the system&#x27;s x axis. This is not an absolute position in the universe.</value>
        [DataMember(Name="x", EmitDefaultValue=false)]
        public int? X { get; set; }

        /// <summary>
        /// Relative position of the waypoint on the system&#x27;s y axis. This is not an absolute position in the universe.
        /// </summary>
        /// <value>Relative position of the waypoint on the system&#x27;s y axis. This is not an absolute position in the universe.</value>
        [DataMember(Name="y", EmitDefaultValue=false)]
        public int? Y { get; set; }

        /// <summary>
        /// Waypoints that orbit this waypoint.
        /// </summary>
        /// <value>Waypoints that orbit this waypoint.</value>
        [DataMember(Name="orbitals", EmitDefaultValue=false)]
        public List<WaypointOrbital> Orbitals { get; set; }

        /// <summary>
        /// The symbol of the parent waypoint, if this waypoint is in orbit around another waypoint. Otherwise this value is undefined.
        /// </summary>
        /// <value>The symbol of the parent waypoint, if this waypoint is in orbit around another waypoint. Otherwise this value is undefined.</value>
        [DataMember(Name="orbits", EmitDefaultValue=false)]
        public string Orbits { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SystemWaypoint {\n");
            sb.Append("  Symbol: ").Append(Symbol).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  X: ").Append(X).Append("\n");
            sb.Append("  Y: ").Append(Y).Append("\n");
            sb.Append("  Orbitals: ").Append(Orbitals).Append("\n");
            sb.Append("  Orbits: ").Append(Orbits).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SystemWaypoint);
        }

        /// <summary>
        /// Returns true if SystemWaypoint instances are equal
        /// </summary>
        /// <param name="input">Instance of SystemWaypoint to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SystemWaypoint input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Symbol == input.Symbol ||
                    (this.Symbol != null &&
                    this.Symbol.Equals(input.Symbol))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.X == input.X ||
                    (this.X != null &&
                    this.X.Equals(input.X))
                ) && 
                (
                    this.Y == input.Y ||
                    (this.Y != null &&
                    this.Y.Equals(input.Y))
                ) && 
                (
                    this.Orbitals == input.Orbitals ||
                    this.Orbitals != null &&
                    input.Orbitals != null &&
                    this.Orbitals.SequenceEqual(input.Orbitals)
                ) && 
                (
                    this.Orbits == input.Orbits ||
                    (this.Orbits != null &&
                    this.Orbits.Equals(input.Orbits))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Symbol != null)
                    hashCode = hashCode * 59 + this.Symbol.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.X != null)
                    hashCode = hashCode * 59 + this.X.GetHashCode();
                if (this.Y != null)
                    hashCode = hashCode * 59 + this.Y.GetHashCode();
                if (this.Orbitals != null)
                    hashCode = hashCode * 59 + this.Orbitals.GetHashCode();
                if (this.Orbits != null)
                    hashCode = hashCode * 59 + this.Orbits.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
