/* 
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * OpenAPI spec version: 2.3.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2017Data
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse2017DataTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2017Data
        //private InlineResponse2017Data instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2017Data
            //instance = new InlineResponse2017Data();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2017Data
        /// </summary>
        [Test]
        public void InlineResponse2017DataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2017Data
            //Assert.IsInstanceOfType<InlineResponse2017Data> (instance, "variable 'instance' is a InlineResponse2017Data");
        }


        /// <summary>
        /// Test the property 'Cooldown'
        /// </summary>
        [Test]
        public void CooldownTest()
        {
            // TODO unit test for the property 'Cooldown'
        }
        /// <summary>
        /// Test the property 'Extraction'
        /// </summary>
        [Test]
        public void ExtractionTest()
        {
            // TODO unit test for the property 'Extraction'
        }
        /// <summary>
        /// Test the property 'Cargo'
        /// </summary>
        [Test]
        public void CargoTest()
        {
            // TODO unit test for the property 'Cargo'
        }
        /// <summary>
        /// Test the property 'Events'
        /// </summary>
        [Test]
        public void EventsTest()
        {
            // TODO unit test for the property 'Events'
        }

    }

}
